<!-- resources/views/pdf/conference_room_report.blade.php -->


<html>
<head>
    <title> Conference Room Report </title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        h1 {
            text-align: center;
            margin-top: 20px; /* Adjust margin-top as needed */
        }
        table {
            width: 100%;
            border-collapse: collapse;
            position: relative; /* Ensure relative positioning for the table */
        }
        th, td {
            border: 1px solid #dddddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: #f2f2f2;
            text-align: center;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <h1>Conference Room Report</h1>
  
    <table>
        <thead>
            <tr>
                <th>Booking ID</th>
                <th>Organizer</th>
                <th>Conference Room</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Participant Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach($bookings as $booking)
                <tr>
                    <td>{{ $booking->booked_confrence_room_id }}</td>
                    <td>{{ $booking->username }}</td>
                    <td>{{ $booking->conference_room }}</td>
                    <td>{{ $booking->start_date }}</td>
                    <td>{{ $booking->end_date }}</td>
                    <td>{{ $booking->start_time }}</td>
                    <td>{{ $booking->end_time }}</td>
                    <td>
                        @foreach(json_decode($booking->participant_names) as $participantName)
                            {{ $participantName }}<br>
                        @endforeach
                    </td>
                </tr>
            @endforeach
        </tbody>
        
        <tfoot>
            <tr class="footer">
                <td colspan="8">
                    <center>Generated by Your Application &mdash; {{ date('Y-m-d H:i:s') }}</center>
                </td>
            </tr>
        </tfoot>
    </table>
</body>
</html>
